  %% fisatproject.cls
  %% Copyright 2015 Jestin Joy
  %
  % This program may be distributed and/or modified under the
  % conditions of the LaTeX Project Public License, either version 1.2
  % of this license or (at your option) any later version.
  % The latest version of this license is in
  %   http://www.latex-project.org/lppl.txt
  % and version 1.2 or later is part of all distributions of LaTeX 
  % version 1999/12/01 or later.
  %
  % This program consists of the file fisatproject.cls

\ProvidesClass{mins}[1/1/2015]
\NeedsTeXFormat{LaTeX2e}

%\DeclareOption*{\InputIfFileExists{\CurrentOption.min}{}{
%\PassOptionsToClass{\CurrentOption}{report}}}

\PassOptionsToClass{notitlepage}{report}

\ProcessOptions \relax

\LoadClass[a4paper,12pt]{report}
%[left=.5in,right=.5in,top=1in,bottom=1in]
\RequirePackage[top=.8in,bottom=.7in]{geometry}
\RequirePackage{graphicx}
\RequirePackage{url,fancyhdr}
\RequirePackage{titlesec}
\RequirePackage{listings}
\RequirePackage[toc,page]{appendix}


\titleformat{\chapter}[display]
  {\normalfont\Large\bfseries\filcenter}{\chaptertitlename\ \thechapter}{20pt}{\Large}
\titlespacing*{\chapter}
  {0pt}{30pt}{20pt}

\def\title#1{\gdef\@title{#1}\gdef\stored@title{#1}}
\def\author#1{\gdef\@author{#1}\gdef\stored@author{#1}}
\def\team#1{\gdef\@team{#1}\gdef\stored@team{#1}}
\def\guide#1{\gdef\@guide{#1}\gdef\stored@guide{#1}}



\pagenumbering{gobble}

\def\@maketitle{%
  %\vskip 2em%
  \vspace{2cm}
  \begin{center}%
    {\LARGE \@title \par}%
    \vfill
\vskip 1.5em%
\textit{A Internship report submitted in partial fulfillment of the requirements for\\[.2cm]
	the award of the degree of}\\[1.5cm]
	{\Large \bf \itshape{{Bachelor of Technology}}}\\[.5cm]
\textit{in}\\[.5cm]
{\Large \bf \itshape{{Computer Science \& Engineering}}}\\[1.5cm]
    \vskip 1.5em%
    {\large
      \lineskip .5em%
      Submitted by\\[.2cm]
      \begin{tabular}[t]{c}%
        \@team
      \end{tabular}\par}%
    \vskip 1em%
   % {\large \@date}%
   \thispagestyle{empty}
  \par
  \vfill
  \includegraphics[scale=.15]{fisat}\\[.5cm]
  \large \bfseries{FEDERAL INSTITUTE OF SCIENCE AND TECHNOLOGY (FISAT)}\\
  \small \bfseries{ANGAMALY-683577}\\[.5cm]
  \small {\textit{Affiliated to}}\\[.5cm]
  \large \bfseries{APJ ABDUL KALAM TECHNOLOGICAL UNIVERSITY}\\
  \small \bfseries{Kerala -695016}\\
  \end{center}
  }


\newcommand{\makecert}{
\newpage
\thispagestyle{plain}
\vspace{3cm}
\begin{center}
{\large FEDERAL INSTITUTE OF SCIENCE AND TECHNOLOGY (FISAT)}\\
Mookkannoor(P.O), Angamaly-683577
\end{center}
\begin{center}
\includegraphics[scale=.15]{fisat}\\
\vspace{2cm}
\textbf{CERTIFICATE}
\end{center}
\vspace{1.5cm}
 This is to certify the Internship report entitled ``\textbf{\stored@title}'' is a bonafide report of the Internship presented during IV$^{th}$ semester by \textbf{\stored@author}, in partial fulfillment of the requirements for the award of the degree of Bachelor of Technology (B.Tech) in Computer Science \& Engineering.\\[3cm]

\hfill \textbf{Dr. Prasad J C}\\
Staff in Charge \hfill Head of the Department


\vspace{2cm}
\begin{flushleft}
\textbf{Place}:\\
\textbf{Date}:
\end{flushleft}

}

\pagestyle{fancy}
\fancyhf{}
\lhead{\stored@title}
\lfoot{ Computer Science \& Engineering | FISAT}
\rfoot{\thepage}
